# Generated by Django 6.0.5 on 2026-06-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_remove_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
